- main.py
BookData 객체 isFull(self), insert_record(self, BookRecord) 추가
add_book() 함수 생성 및 디버깅 완료
> input 함수들 인자 통일 및 수정

- baseline.py
closed #8 
<br/>
<br/>
<br/>
```python
abc
```
<br/>
<br/>
<br/>
<br/>
> [Chore] #8 - Package Import 구문 추가

- main.py
closed #11 
<br/>
MyDate 클래스 덧셈 연산자 구현
<br/>
MyDate 클래스 `__add__` 메서드 구현
<br/>
```python
def __add__(self, days):
if not isinstance(days, int):
raise TypeError("날짜에 더할 일수는 정수여야 합니다.")
day = self.day
month = self.month
year = self.year
while days > 0:
days_in_current_month = 29 if (month == 2 and self.is_leap_year(year)) else [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31][month - 1]
if day + days <= days_in_current_month:
day += days
days = 0
else:
days -= (days_in_current_month - day + 1)
day = 1
month += 1
if month > 12:
month = 1
year += 1
return MyDate(year, month, day)
```
아래와 같이 사용 가능
```python
borrow_date = MyDate.from_str("2024-11-1")
return_date = borrow_date + 7
if borrow_date + 7 == return_date: return True
```
<br/>
X
<br/>
X
<br/>
> [Feat] #11 - MyDate 클래스 덧셈 연산자 구현

- main.py
삭제, 대출 프롬프트 항목별 input 함수까지 구현 완료
> deleteBook, borrowBook

- jiwon_main.py
> def check_string_validate,check_year_validate 함수 에러 수정

- main.py
closed #38 
<br/>
Merge
<br/>
- 수정 파트 적용
<br/>
> [Merge] #38 - Merge

- main.py
closed #40 
<br/>
borrow error
cancel
<br/>
- Fix borrow error
- Add cancel
<br/>
> [Fix] #40 - Merge, Add Cancel, Fix bug

- main.py
closed #47 
<br/>
현재날짜 입력 및 날짜 무결성 검사 구현
<br/>
- 현재 날짜 입력 함수 수정
- 파일 무결성 검사에서 현재 날짜 필요한 부분 삭제
- 현재날짜 입력 시 데이터와 비교해 무결성 검사 
<br/>
X
<br/>
X
<br/>
> [Feat] #47 - 현재날짜 입력 및 날짜 무결성 검사 구현

- main.py
closed #50 
<br/>
파일 컨벤션 수정 및 필요없는 print 제거
<br/>
- 파일 컨벤션 수정
- 파일 무결성 검사 내 print문 verbose 처리
- `BookData.check_data_file(verbose=True)` 시 디버그 프린트
- 취소 입력자 `"X"` 및 대출일 `7` 전역상수화
<br/>
X
<br/>
X
<br/>
> [Refactor] #50 - 파일 컨벤션 수정 및 필요없는 print 제거

- main.py
closed #53 
<br/>
MyDate 클래스 내 연도 조건 상수 수정
<br/>
- 1852로 잘못 되어있던 상수 수정
<br/>
X
<br/>
X
<br/>
> [Fix] #53 - MyDate 클래스 내 연도 조건 상수 수정

- main.py
책 목록에 존재하는 고유번호에 대해 특정시 ERROR: 해당 고유번호를 가진 책이 존재하지 않습니다. 출력하면서 특정 안됨
<br/>
오류 수정
<br/>
<br/>
```python
def input_book_id(self, input_message: str, flag: int) -> str: # 기존
def input_book_id(self, input_message: str, flag: int) -> int: # 변경
if flag == 0 and self.search_id(book_id): # 기존
if flag == 0 and self.search_id(book_id_int): # 변경
if flag == 1 and self.search_id(book_id) is None: # 기존
if flag == 1 and self.search_id(book_id_int) is None: # 변경
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #59 - 고유번호로 책 특정이 안되는 오류 수정

- main.py
closed #61 
<br/>
- 수정 전
def input_date(self):
- 수정 후
def input_date(bookData: BookData):
<br/>
- 인자 수정
> [Fix] #61 - input_date의 인자 수정

- Libsystem_Main.py
입력과 공백 입력에 대한 오류 메시지 구분 출력 오류, 전화번호 뒤로가기 추가 필요
<br/>
오류 수정
<br/>
<br/>
```python
title = input(input_message)
if not title:  # 입력값이 비어있는 경우
print("ERROR: 책의 제목은 1글자 이상이어야 합니다.")
return None
title = title.strip()
if not title:  # 공백을 제거한 후 비어있는 경우
print("ERROR: 책의 제목은 공백일 수 없습니다.")
return None
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #71 - 입력과 공백 입력에 대한 오류 메시지 구분 출력 오류, 전화번호 뒤로가기

- Libsystem_Main.py
고유번호 입력에 \t 붙을 시 오류 발생 
<br/>
오류 수정
<br/>
<br/>
```python
if book_id.strip() == CANCEL:
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #75 - 고유번호 입력에 \t붙을시 오류 발생

- Libsystem_Main.py
고유번호 입력값이 CANCEL인경우에 대한 에러 메시지 수정 필요
<br/>
오류 수정
<br/>
<br/>
```python
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #81 - 고유번호 입력값이 CANCEL인경우에 대한 에러 메시지 수정

- Libsystem_Main.py
closed #83 
<br/>
데이터 파일 홈 경로에 저장 기능 구현
<br/>
데이터를 홈 파일에 저장하고 읽도로 구현
<br/>
```python
""" Windows 기준 사용자의 Home 경로 가져오는 함수 """
def get_user_home_path() -> str:
home_path = os.path.expanduser("~")
return home_path
""" main """
if __name__ == "__main__":
try:
dir_path = get_user_home_path()
if dir_path is None or len(dir_path) == 0:
raise ValueError 
except Exception as e:
dir_path = "./"
bookData = BookData(file_path=opj(dir_path, "Libsystem_data.txt"))
```
<br/>
X
<br/>
X
<br/>
> [Feat] #83 - 데이터 파일 홈 경로에 저장 기능 구현

- Libsystem_Main2.py
closed #97 
<br/>
테이블 분리에 따라 대출 기능을 migration 했습니다
<br/>
- 대출 기능 migration
<br/>
X
<br/>
X
<br/>
> [Feat] #97 - 대출 기능 Migration

- Libsystem_Main2.py
closed #97 
<br/>
테이블 분리에 따라 반납 기능을 migration 했습니다
<br/>
- 반납 기능 migration
<br/>
X
<br/>
X
<br/>
> [Feat] #99 - 반납 기능 Migration

- Libsystem_Main2.py
closed #101 
<br/>
테이블 분리에 따라 추가 기능을 migration 했습니다
<br/>
- 추가 기능 migration
<br/>
X
<br/>
X
<br/>
> [Feat] #101 - 추가 기능 Migration

- Libsystem_Main2.py
closed #96 
<br/>
테이블 분리에 따라 수정 기능을 migration 했습니다
<br/>
- 수정 기능 migration
- 헷갈리는 인스턴스 검색 함수명 변경
<br/>
X
<br/>
X
<br/>
> [Feat] #96 - 수정 기능 Migration

- Libsystem_Main2.py
> 7 prompt file

- Libsystem_Main2.py
> [Chore] #112

- Libsystem_Main2.py
기존 __add__ 와 __sub__을 활용하기에는 정수와 MyDate연산이 불가능해서 수정함.
아직 대출, 반납에는 자잘한 오류가 많아서 코드 수정이 필요.
우선은 연체 페널티의 기능만 구현된 코드 올림.
<br/>
<br/>
<br/>
```python
abc
```
<br/>
<br/>
<br/>
<br/>
> [Feat] #116 - 연체 페널티 기능 구현

- Libsystem_Main2.py
> [Fix] #120 - 추가 프롬프트 완료

- Libsystem_Main2.py
<br/>
<br/>
<br/>
```python
overdue_books = self.search_borrowing_book_ids_by_user_id(borrower_id, overdue_only=True)
```
<br/>
<br/>
<br/>
<br/>
> [Chore] #123 - 불필요한 출력 삭제

- Libsystem_Main2.py
closed #125 
<br/>
데이터 파일에 쓰기 함수 연결
<br/>
`fetch_data_file()` 함수 구현
<br/>
X
<br/>
X
<br/>
> [Feat] #125 - 데이터 파일에 쓰기 함수 연결

- Libsystem_Main2.py
> [Fix] #128

- Libsystem_Main2.py
closed #130 
<br/>
수정 시 새로운 출판사 데이터 추가되지 않는 문제
<br/>
1. 수정할 출판사 입력
2. 출판사 이름이 같은 레코드 존재 시 해당 출판사로
3. 만약 존재하지 않을 경우 새로운 출판사 인스턴스 생성
4. 수정 확인 시 추가
<br/>
확인 후 머지해주시면 감사드리겠습니다
<br/>
X
<br/>
> [Fix] #130 - 수정 시 새로운 출판사 데이터 추가되지 않는 문제

- Libsystem_Main2.py
closed #132 
<br/>
책 삭제 시 실제 데이터 삭제되는 문제 수정
<br/>
(기존) 리스트에서 삭제할 레코드 삭제
(이후) `BookRecord.deleted = True`, `BookRecord.deleted_date = self.today` 로 수정
<br/>
X
<br/>
X
<br/>
> [Fix] #132 - 책 삭제 시 실제 데이터 삭제되는 문제 수정

- Libsystem_Main2.py
> [Fix] #138 - 저자 오류 메세지 수정

- Libsystem_Main2.py
> [Fix] #142 - 추가 프롬프트 완료

- Libsystem_Main2.py
closed #147 
<br/>
데이터 파일 쓰기 함수 오류 수정
<br/>
1. ISBN 쓸 때 `.zfill(2)`로 두 자리로 작성
2. Nullable 데이터 작성 시 `None`인 경우 `""`로 작성
<br/>
X
<br/>
X
<br/>
> [Fix] #147 - 데이터 파일 쓰기 함수 오류 수정

- Libsystem_Main2.py
closed #150 
<br/>
MyDate __str__ 함수 월, 일 두 자리 반환하도록 수정
<br/>
<br/>
프로그램 상 오류는 아니지만 사소한 수정
<br/>
X
<br/>
> [Chore] #150 - MyDate __str__ 함수 월, 일 두 자리 반환하도록 수정

- Libsystem_Main2.py
closed #148 
<br/>
데이터 파일 무결성 순서 조정 및 검사 실패 시 프로그램 종료되도록 수정
<br/>
- 데이터 파일 무결성 순서 조정 
- 검사 실패 시 프로그램 종료되도록 수정
- 참조 간 무결성 검사 구현
- 기타 사소한 오류 수정
<br/>
X
<br/>
X
<br/>
> [Fix] #148 - 데이터 파일 무결성 순서 조정 및 검사 실패 시 프로그램 종료되도록 수정

- Libsystem_Main2.py
숫자 여부는 isdigit()로 하니 문자열인 경우와 숫자가 0보다 작은 경우가 구분이 안돼서 합쳤습니다.
> 파일 무결성 중복 및 숫자 여부 확인 코드 수정

- Libsystem_Main2.py
대출 중인 책 목록 출력 수정
<br/>
<br/>
<br/>
```python
abc
```
<br/>
<br/>
<br/>
<br/>
> [Fix] #171 - 대출 중인 책 목록 출력 수정

- Libsystem_Main2.py
closed #184 
<br/>
저자 없는 경우 "-"로 출력하도록 수정
<br/>
- `convert_author_ids_to_name_id()` 함수 수정
- `print_book()` 함수 수정
<br/>
```python
def convert_author_ids_to_name_id(self, author_ids: list[int]) → str:
names = []
if len(author_ids) == 0:
return "-"
for author_id in author_ids:
author = self.search_author_by_id(author_id)
if author:
names.append(f"{author.name} #{author.author_id}")
return " & ".join(names)```
def print_book(self, book_id: int, include_borrow: bool=False):    
if len(author_data) == 0:
return_str += "-"
else:
return_str += f"{' & '.join(list(map(lambda x: f'{x.name} #{x.author_id}', author_data)))}/"
<br/>
X
<br/>
X
<br/>
> [Fix] #184 - 저자 없는 경우 "-"로 출력하도록 수정

- Libsystem_Main2.py
closed #185 
<br/>
삭제된 책 연혁 조회되지 않는 오류 수정
<br/>
- 책 고유번호 입력 함수에 삭제 여부 포함 옵션화
- 책 고유번호 검색해서 책 인스턴스 반환 함수 삭제 여부 포함 옵션화
<br/>
```python
def search_book_by_id(self, book_id, include_deleted: bool=False) → BookRecord:
"""_summary_ 
책 고유번호로 책 인스턴스 반환
"""
if include_deleted:
for book in self.book_table:
if book.book_id == book_id:
return book
else:
for book in self.book_table:
if book.book_id == book_id and (not book.deleted or (book.deleted and book.delete_date > self.today)):
return book
return None```
<br/>
x
<br/>
x
<br/>
> [Fix] #185 - 책 ID 검사 시 삭제 여부 옵션화 및 오류 수정

- Libsystem_Main.py
> [Fix] #198 - 추가 프롬프트 넘버링 수정

- Libsystem_Main.py
> [Fix] #204 - 추가 프롬프트에서 저자에서 엔터쳤을 때 오류 수정

- Libsystem_Main.py
> [Fix] #206 - 추가 프롬프트 버그 수정
